custom:
  - https://www.krishnamohanproductions.com/donate
  - https://www.paypal.com/paypalme/KrishnamohanYag?country.x=IN&locale.x=en_GB
  - https://buymeacoffee.com/krishnamohanz
  - https://razorpay.me/@krishnamohanyagneswaran
